name             'dev2cb'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures dev2cb'
long_description 'Installs/Configures dev2cb'
version          '0.1.0'
depends          'java'
depends          'git'
